[pytest]
addopts =
    -v
    -s
    --tb=short
    --maxfail=1
    --strict-markers
    --alluredir=C:/Users/Amitu/PycharmProjects/playwright-e2e-framework/allure-results

testpaths = tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: Smoke tests
    regression: Regression tests
    api: API tests
    ui: UI tests
    e2e: End to end tests
    contract: Contract tests 👑🔥